lecture/urls.py
from django.urls import path
from . import views

app_name='lecture'

urlpatterns = [
    path('', views.main, name='list'),
    path('detail/<int:lecture_id>', views.detail, name='detail'),
    path('addcomment/<int:lecture_id>', views.createCommentToLecture, name='addComment'),
    path('updatecomment/<int:comment_id>', views.updateComment, name='updateComment'),
    path('deletecomment/<int:comment_id>', views.deleteComment, name='deleteComment'),
    path('getcomment/<int:comment_id>', views.getComment, name='getComment'),
    path('searchlecture/', views.searchLectrue, name='searchLectrue'),
    path('mypage/<int:user_id>',views.mypage, name='mypage'),

]

lecture/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

class College(models.Model):
    college_title = models.CharField(max_length=30)

    def __str__(self):
        return self.college_title

class Department(models.Model):
    college_title = models.ForeignKey(College, on_delete=models.CASCADE, related_name='dept')
    department_title = models.CharField(max_length=30)

    def __str__(self):
        return self.department_title

class Lecture(models.Model):
    title = models.CharField(max_length=30)
    est_year = models.CharField(max_length=5)
    session = models.CharField(max_length=5)
    department_title = models.CharField(max_length=30)
    category = models.CharField(max_length=10)
    unit = models.CharField(max_length=10)
    prof = models.CharField(max_length=10)
    grade = models.CharField(max_length=10)
    class_prog = models.CharField(max_length=30)
    class_eval = models.CharField(max_length=30)
    score = models.FloatField(validators=[MinValueValidator(0), MaxValueValidator(5)], default=0)

    def __str__(self):
        return self.title

class LectureComment(models.Model):
    lecture = models.ForeignKey(Lecture, on_delete=models.CASCADE, related_name='comment')
    star = models.FloatField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    content = models.TextField()
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='comment')
    created_at = models.DateTimeField(auto_now_add=True)

lecture/forms.py
from django import forms
from .models import Lecture, LectureComment
from .widgets import starWidget

from django.core.validators import MinValueValidator, MaxValueValidator

class LectureCommentForm(forms.Form):
    star = forms.FloatField(validators=[MinValueValidator(0), MaxValueValidator(5)], widget = starWidget)
    content = forms.CharField(max_length=50, widget=forms.Textarea) 

lecture/views.py
import openpyxl
from django.core import serializers
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .models import Lecture, LectureComment, College, Department
from .forms import LectureCommentForm
from accounts.models import Profile
from django.contrib.auth.models import User
from .paginator import my_paginator

def evalScore(lecture_id):
    lecture = Lecture.objects.get(pk=lecture_id)
    comments = lecture.comment.all()
    count = comments.count()
    score = 0

    for comment in comments:
        score += comment.star
    try:
        return score/count
    except ZeroDivisionError:
        return 0

def main(request):
    lecture_list = Lecture.objects.all()

    page = request.GET.get('page', 1)

    lectures, page_range = my_paginator(lecture_list, page, num=8, page_num_range=10)
    return render(request, 'lecture/main.html', {
        'lectures' : lectures,
        'page_range':page_range,
    })


@login_required
def detail(request, lecture_id):
    lecture = Lecture.objects.get(pk=lecture_id)
    form = LectureCommentForm()

    return render(request, 'lecture/detail.html', {
        'lecture' : lecture,
        'form' : form,
    })

def createCommentToLecture(request, lecture_id):
    lecture = Lecture.objects.get(pk=lecture_id)
    form = LectureCommentForm()

    if request.method == "POST":
        form = LectureCommentForm(request.POST)
        comment, created = LectureComment.objects.get_or_create(lecture=lecture, author=request.user, defaults={
            'star': 0,
            'content': 'none',
        })
        print(created)
        if form.is_valid() and created:
            comment.star = form.cleaned_data['star']
            comment.content = form.cleaned_data['content']
            comment.author = request.user
            comment.save()

            lecture.score = evalScore(lecture.id)
            lecture.save()
            
            jsonData = serializers.serialize('json',lecture.comment.all(),indent=2, use_natural_foreign_keys=True, use_natural_primary_keys=True)
            return HttpResponse(jsonData, content_type='application/json')
        else:
            return redirect('lecture:detail', lecture.pk)
    return render(request, 'lecture/detail.html', {
    'lecture' : lecture,
    'form' : form,
    })

def updateComment(request, comment_id):
    comment_queryset = LectureComment.objects.filter(pk=comment_id)
    comment = comment_queryset[0]
    
    if request.user == comment.author:
        if request.method == "POST":
            form = LectureCommentForm(request.POST)
            if form.is_valid():
                comment.content = request.POST['content']
                comment.author = request.user
                comment.save()

                jsonData = serializers.serialize('json',comment_queryset,indent=2, use_natural_foreign_keys=True, use_natural_primary_keys=True)
                return HttpResponse(jsonData, content_type='application/json')
            else:
                print(form.errors)
                return redirect('lecture:detail', comment.lecture.id)
    return render(request, 'lecture/detail.html', {
    'lecture' : lecture,
    'form' : form,
    })

def deleteComment(request, comment_id):
    comment = LectureComment.objects.get(pk=comment_id)
    lecture = comment.lecture
    if request.user == comment.author:
        comment.delete()
        lecture.score = evalScore(lecture.id)
        lecture.save()
    return redirect('lecture:detail', lecture.id)

def getComment(request, comment_id):
    lecture = LectureComment.objects.filter(pk=comment_id)
    jsonData = serializers.serialize('json',lecture,indent=2, use_natural_foreign_keys=True, use_natural_primary_keys=True)
    return HttpResponse(jsonData, content_type='application/json')


def searchLectrue(request):

    category = request.GET.get('category','')
    data = request.GET.get('search_data','')

    if data == '' or category == '':
        lectures = Lecture.objects.all()
    else:
        if category == '강의명':
            lectures = Lecture.objects.filter(title__contains=data)
        else:
            lectures = Lecture.objects.filter(prof=data)
    
    return render(request, 'lecture/main.html', {
        'lectures' : lectures,
    })

@login_required
def mypage(request, user_id):
    user = User.objects.get(pk = user_id)
    return render(request, 'lecture/mypage.html', {
        'user' : user,
    })

templates/lecture/detail.html
{% extends 'base.html' %}
{% load static %}

{% block extra_js %}

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
<script type="text/javascript"
    src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@0.4.0/dist/chartjs-plugin-datalabels.min.js"></script>
<script src="{% static 'js/detail.js' %}">
</script>

{% endblock extra_js %}

{% block content %}

<h1 class="title">교과목 정보</h1>
<table>
    <thead>
        <tr class="category">강의명: </tr> {{ lecture.title }}
    </thead>
    <tbody>
        <tr>
            <td class="category">개설연도</td>
            <td colspan="2">{{ lecture.est_year }} - {{ lecture.session }}</td>
            <td class="category">개설학과</td>
            <td>{{ lecture.department_title }}</td>
        </tr>
        <tr>
            <td class="category">담당교수</td>
            <td colspan="2">{{ lecture.prof }}</td>
            <td class="category">이수구분</td>
            <td colspan="2">{{ lecture.unit }}</td>
        </tr>
        <tr>
            <td class="category">개설학년</td>
            <td colspan="2" style="color: blue;">{{ lecture.grade }}</td>
            <td class="category">학점시수</td>
            <td colspan="2">{{ lecture.unit }}</td>
        </tr>
        <tr>
            <p>별점:⭐⭐⭐⭐⭐{{lecture.score}}</p>
        </tr>
    </tbody>
</table>
</div>

<div class="container">
    <div>
        <canvas id="progress" width="300"></canvas>
    </div>
</div>

<div class="container">
    <div>
        <canvas id="evaluation" width="500" height="500"></canvas>
    </div>
</div>

<div class="container">
    <h4 class="title">댓글 작성</h4>

    <form name="commentForm" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="button" value="작성" onclick="addComment({{ lecture.id }})">
    </form>
</div>

<div class="container">
    <hr>
    <div id="comment-box">
        {% for comment in lecture.comment.all %}

        <div id="{{comment.id}}" class="comment">
            {{comment.author}}
            {% if request.user == comment.author %}
            <a href="{% url 'lecture:deleteComment' comment.id %}">삭제</a>
            <a id="{{comment.id}}" href="javascript:" onclick="commentEdit(this)">수정</a>
            {% endif %}
            <div class="star">{{ comment.star }}</div>
            <div class="content">{{ comment.content }}</div>

        </div>
        <hr>
        {% endfor %}
    </div>
</div>

<script type="text/javascript">

    let class_prog = $.map('{{lecture.class_prog}}'.split('&amp;'), function (value) {
        return parseInt(value, 10);
    });
    let class_eval = $.map('{{lecture.class_eval}}'.split('&amp;'), function (value) {
        return parseInt(value, 10);
    });

    let ctx = document.getElementById('progress');
    let ctx2 = document.getElementById('evaluation')
    ctx.width = 300;
    ctx.height = 300;
    ctx2.width = 300;
    ctx2.height = 300;


    let progress = new Chart(ctx, {
        type: 'pie',
        data: {
            labels: ["강의", "토의/토론", "실험/실습", "현장학습", "개별/팀별발표", "기타"],
            datasets: [{
                data: class_prog,
                backgroundColor: ["#FF3D67", "#FF9124", "#FFC233", "#22CECE", "#059BFF", "#8142FF"],
                borderColor: "#fff"
            }],
        },
        options: {
            responsive: false,
            title: {
                display: true,
                text: '강의진행',
                fontSize: 20,
            },
            legend: {
                position: 'bottom',
            },
            plugins: {
                datalabels: {
                    formatter: function (value, ctx) {
                        let datasets = ctx.chart.data.datasets;
                        if (datasets.indexOf(ctx.dataset) === datasets.length - 1) {
                            let sum = datasets[0].data.reduce((a, b) => a + b, 0);
                            let percentage = Math.round((value / sum) * 100) + '%';
                            if (percentage == '0%') {
                                return '';
                            }
                            return percentage;
                        } else {
                            return percentage;
                        }
                    },
                    color: '#fff',
                },
            }
        },
    });

    let evaluation = new Chart(ctx2, {
        type: 'pie',
        data: {
            labels: ["중간고사", "기말고사", "출석", "퀴즈", "과제", "기타"],
            datasets: [{
                data: class_eval,
                backgroundColor: ["#FF3D67", "#FF9124", "#FFC233", "#22CECE", "#059BFF", "#8142FF"],
                borderColor: "#fff"
            }],
        },
        options: {
            responsive: false,
            title: {
                display: true,
                text: '평가방법',
                fontSize: 20,
            },
            legend: {
                position: 'bottom',
            },
            plugins: {
                datalabels: {
                    formatter: function (value, ctx2) {
                        let datasets = ctx2.chart.data.datasets;
                        if (datasets.indexOf(ctx2.dataset) === datasets.length - 1) {
                            let sum = datasets[0].data.reduce((a, b) => a + b, 0);
                            let percentage = Math.round((value / sum) * 100) + '%';
                            if (percentage == '0%') {
                                return '';
                            }
                            return percentage;
                        } else {
                            return percentage;
                        }
                    },
                    color: '#fff',
                },
            }
        },
    });

</script>

{% endblock %}

templates/lecture/main.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h3 class="title">강의 검색!</h3>

    <form action="{% url 'lecture:searchLectrue' %}" method="GET">
        <select name="category">
            <option>강의명</option>
            <option>교수</option>
        </select><br><br>
            <input name="search_data" class="input" type="text" placeholder="강의명/교수명으로 검색해보세요">
            <input type="submit" value="검색">
    </form>
</div>
{% for lecture in lectures %}
<div style="margin-top: 10%;">
    <div class="box" style="border: 1px solid black;">
        <span>개설년도: 2020-1 | 교수 : 누구씨 | 전공필수<span>
                <br>
                <a href="{% url 'lecture:detail' lecture.id %}">
                    <h2>{{lecture.title}}</h2>
                </a>
                <hr>
                <span style="float: right;">별점: ⭐⭐⭐⭐⭐</span>
    </div>
</div>

{% endfor %}

{% endblock %}

templates/lecture/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<div class="container">
    <hr>
    <div id="comment-box">
        {% for comment in user.comment.all %}

        <div id="{{comment.id}}" class="comment" style="padding:15px;">
            <a href={% url 'lecture:detail' comment.lecture.id %}>{{comment.lecture}}</a>
            <div class="star" style="margin-top:5px;margin-bottom:5px;">
                {% if comment.star > 4 %}
                ⭐⭐⭐⭐⭐
                {% elif comment.star > 3 and comment.star <= 4%}
                ⭐⭐⭐⭐
                {% elif comment.star > 2 and comment.star <= 3%}
                ⭐⭐⭐
                {% elif comment.star > 1 and comment.star <= 2%}
                ⭐⭐
                {% elif comment.star > 0 %}
                ⭐
                {% else %}

                {% endif %}
            </div>            
            <div class="content">{{ comment.content }}</div>

        </div>
        <hr>
        {% endfor %}
    </div>
</div>


{% endblock %}